name: valkey_client
description: Smart client for Valkey and Redis. Supports Standalone, Sentinel, and Cluster modes.
version: 2.0.0
repository: https://github.com/infradise/valkey_client
homepage: https://keyscope.dev
license: Apache-2.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  async: ^2.13.0
  dart_flutter_team_lints: ^3.5.2
  lints: ^6.0.0
  stream_channel: ^2.1.4
  test: ^1.25.0