name: valkey_client
description: A modern, production-ready Dart client for Valkey (9.0.0+). Fully Redis 7.x compatible.
version: 1.2.0

repository: https://github.com/infradise/valkey_client
homepage: https://visualkube.com/opensource/valkey_client

topics:
  - valkey
  - client
  - redis
  - sentinel
  - cluster

environment:
  sdk: '>=3.0.0 <4.0.0'

license: Apache-2.0

# We don't have any dependencies... yet.
# dependencies:

dev_dependencies:
  async: ^2.13.0
  dart_flutter_team_lints: ^3.5.2
  lints: ^6.0.0
  stream_channel: ^2.1.4
  test: ^1.25.0