name: valkey_client
description: A high-performance, cluster-aware Dart client for Redis and Valkey.
version: 2.5.0
repository: https://github.com/infradise/valkey_client
homepage: https://github.com/infradise/valkey_client
issue_tracker: https://github.com/infradise/valkey_client/issues
# documentation: https://github.com/infradise/valkey_client/wiki

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  async: ^2.13.0
  dart_flutter_team_lints: ^3.5.2
  lints: ^6.0.0
  stream_channel: ^2.1.4
  test: ^1.25.0